name: fake_process_manager
description: Fake processes in a test
version: 0.1.0
homepage: https://github.com/mmcc007/fake_process_manager
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  process: ^3.0.9
  tool_base: ^1.9.5+3
#  tool_base:
#    path: ../tool_base
  mockito: ^4.1.0
  test: ^1.6.0
dev_dependencies:
  pedantic: ^1.7.0
  tool_base_test:
    git: https://github.com/mmcc007/tool_base_test.git
#    path: ../tool_base_test